### ISSUE TITLE
consider sharing more details of the verification

### ISSUE THREAD

**Issue by rabbah** [jthomas/openwhisk-release-verification#3]
when i verified an rc, i got all green check boxes but how do i know to trust the checkmarks?
i can look at the source as one way. it might be useful to also show extra information for each of the checks: signature matches could show expected vs actual so one can also manually verify if necessary.

other suggestions: making it possible to download or view the notice, disclaimer and release.

**Comment by jthomas** [comment]
Adding additional logging output to the verification screen to show details on all stages.

<img width="1112" alt="Screenshot 2019-03-29 at 15 49 27" src="https://user-images.githubusercontent.com/2322/55245089-62c26a80-523a-11e9-98ab-8715baf751fc.png">

**Comment by rabbah** [comment]
👍❤️
